version: '3.7'

networks:
  messaging:
    external: false

services:

  # imap:
  #   build: .
  #   container_name: 'imaphost'
  #   # depends_on:
  #   #   - messagebroker
  #   environment:
  #     IMAP_SERVER_SIMPLE_AUTHORIZATION: 'TRUE'
  #     QUEUE_SERVER_HOSTNAME: 'messagebroker'
  #   hostname: 'imaphost'
  #   networks:
  #     - messaging
  #   ports:
  #     - '143:143'

  imap-debug:
    command: '/usr/local/bin/node --inspect=0.0.0.0:5858 /srv/dist/index.js'
    container_name: 'imapdebug'
    environment:
      QUEUE_PROTOCOL: 'DUMMY'
      # QUEUE_PROTOCOL: 'AMQP'
      # QUEUE_SERVER_HOSTNAME: 'messagebroker'
      # The password below is 'oops'.
      DRIVERLESS_AUTHENTICATION_CREDENTIALS: 'jwilbur:3e51e41a6620077a3693048796face0838c5837be2c4f20c78518c38b62f41c31d7845a5bd4b86513b933f7633f2aad7e91409d64b94cfa9fd2464f5c8758f37'
      IMAP_SERVER_PERMITTED_SASL_MECHANISMS: 'PLAIN DIGEST CRAM-MD5'
      IMAP_SERVER_SIMPLE_AUTHORIZATION: 'TRUE'
    hostname: 'imapdebug'
    image: 'node:11.12.0-alpine'
    networks:
      - messaging
    ports:
      - '143:143'
      - '5858:5858' # For debugging. Comment out when done.
    volumes:
      - '.:/srv:ro'

  messagebroker:
    container_name: 'qhost'
    hostname: 'qhost'
    image: 'rabbitmq:management-alpine'
    networks:
      - messaging
    ports:
      - '5672:5672/tcp'
      - '15672:15672/tcp'
    volumes:
      # Run $env:PWD=$(pwd) on Windows to fix this issue.
      - "${PWD}/configuration/rabbitmq/enabled_plugins.erl:/etc/rabbitmq/enabled_plugins:ro"