version: '3.7'

networks:
  messaging:
    external: false

services:

  imap:
    build: .
    container_name: 'imaphost'
    depends_on:
      - messagebroker
    environment:
      QUEUE_SERVER_HOSTNAME: 'messagebroker'
    hostname: 'imaphost'
    networks:
      - messaging
    ports:
      - '143:143'

  imap-debug:
    command: '/usr/local/bin/node --inspect=0.0.0.0:5858 /srv/dist/index.js'
    container_name: 'imapdebug'
    environment:
      QUEUE_PROTOCOL: 'DUMMY'
    hostname: 'imapdebug'
    image: 'node:11.12.0-alpine'
    ports:
      - '143:143'
      - '5858:5858' # For debugging. Comment out when done.
    volumes:
      - '.:/srv:ro'

  messagebroker:
    container_name: 'qhost'
    hostname: 'qhost'
    image: 'rabbitmq:management-alpine'
    networks:
      - messaging
    ports:
      - '5672:5672/tcp'
      - '15672:15672/tcp'
    volumes:
      - "${PWD}/configuration/rabbitmq/enabled_plugins.erl:/etc/rabbitmq/enabled_plugins:ro"